name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16.x', '18.x', '20.x' ]
    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        git remote set-branches --add origin main
        git fetch
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Dependencies
      run: npm ci
      env:
        NODE_ENV: development
    - name: Unit Tests
      run: npm run test:unit
    - name: Git History Test
      run: npm run test:git-history
    - name: Lockfile Lint Test
      run: npm run test:lockfile
    - name: Lint
      run: npm run test:lint
